/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as DesignPreviewRouteImport } from './routes/design-preview'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignPreviewRoute = DesignPreviewRouteImport.update({
  id: '/design-preview',
  path: '/design-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/chat': typeof ChatRoute
  '/design-preview': typeof DesignPreviewRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/system': typeof SystemRoute
  '/tasks': typeof TasksRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/chat': typeof ChatRoute
  '/design-preview': typeof DesignPreviewRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/system': typeof SystemRoute
  '/tasks': typeof TasksRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/chat': typeof ChatRoute
  '/design-preview': typeof DesignPreviewRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/system': typeof SystemRoute
  '/tasks': typeof TasksRoute
  '/tools': typeof ToolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/chat'
    | '/design-preview'
    | '/logs'
    | '/memory'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/system'
    | '/tasks'
    | '/tools'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/chat'
    | '/design-preview'
    | '/logs'
    | '/memory'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/system'
    | '/tasks'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/chat'
    | '/design-preview'
    | '/logs'
    | '/memory'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/system'
    | '/tasks'
    | '/tools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ChatRoute: typeof ChatRoute
  DesignPreviewRoute: typeof DesignPreviewRoute
  LogsRoute: typeof LogsRoute
  MemoryRoute: typeof MemoryRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  SystemRoute: typeof SystemRoute
  TasksRoute: typeof TasksRoute
  ToolsRoute: typeof ToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-preview': {
      id: '/design-preview'
      path: '/design-preview'
      fullPath: '/design-preview'
      preLoaderRoute: typeof DesignPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ChatRoute: ChatRoute,
  DesignPreviewRoute: DesignPreviewRoute,
  LogsRoute: LogsRoute,
  MemoryRoute: MemoryRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  SystemRoute: SystemRoute,
  TasksRoute: TasksRoute,
  ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
